---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-esphome
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/home-automation/esphome/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  dependsOn:
    - name: production-multus-config
    - name: production-rook-ceph-cluster
    - name: production-volsync
    - name: production-external-secrets-stores
