---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: ${clusterName}
talosVersion: v1.6.1
kubernetesVersion: v1.29.0
endpoint: "https://${clusterName}.${clusterDNSSuffix}:6443"

cniConfig:
  name: none

additionalApiServerCertSans: &san
  - ${clusterEndpointIP}
  - ${clusterName}.${clusterDNSSuffix}
  - "127.0.0.1"
additionalMachineCertSans: *san

nodes:
  # Thinkcentre M910q Core i7 7700t, 32GB RAM, 256GB SSD, 1x1Gbps NIC
  - hostname: k8s-m0.${clusterDNSSuffix}
    ipAddress: 172.16.11.10
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 172.16.11.10/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500

  - hostname: k8s-m1.${clusterDNSSuffix}
    ipAddress: 172.16.11.11
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 172.16.11.11/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500

  - hostname: k8s-m2.${clusterDNSSuffix}
    ipAddress: 172.16.11.12
    installDisk: /dev/sda
    controlPlane: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 172.16.11.12/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500

  ### Master Node
  ### Mixed Thinkcentre M720q & M910x
  ### Core i7 8700t, 64GB RAM, 240GB SSD/512GB NVME (OS), 1x1TB NVME (CEPH), 2x10Gbps Mellanox ConnectX-3 Pro EN, 1x1Gbps NIC
  # M720Q
  - hostname: k8s-w0.${clusterDNSSuffix}
    ipAddress: 172.16.11.13
    installDisk: /dev/sda
    controlPlane: false
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:79:67:75:95
      #       - hardwareAddr: e4:1d:79:67:75:96
      #   dhcp: false
      #   addresses:
      #     - 172.16.11.13/24
      #   routes:
      #     - network: 0.0.0.0/0
      #       gateway: 172.16.11.254
      #   mtu: 1500
      - interface: eth1
        dhcp: false
        addresses:
          - 172.16.11.13/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.13/24
            mtu: 1500
    nodeLabels: &workerLabels
      node-role.kubernetes.io/worker: worker

  # M720Q
  - hostname: k8s-w1.${clusterDNSSuffix}
    ipAddress: 172.16.11.14
    installDisk: /dev/sda
    controlPlane: false
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:85:75:d8:73
      #       - hardwareAddr: e4:1d:85:75:d8:74
      #   dhcp: false
      #   addresses:
      #     - 172.16.11.14/24
      #   routes:
      #     - network: 0.0.0.0/0
      #       gateway: 172.16.11.254
      #   mtu: 1500
      - interface: eth1
        dhcp: false
        addresses:
          - 172.16.11.14/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.14/24
            mtu: 1500
    nodeLabels: *workerLabels

  # M720Q
  - hostname: k8s-w2.${clusterDNSSuffix}
    ipAddress: 172.16.11.15
    installDisk: /dev/sda
    controlPlane: false
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:7a:67:a5:d4
      #       - hardwareAddr: e4:1d:7a:67:a5:d5
      #   dhcp: false
      #   addresses:
      #     - 172.16.11.15/24
      #   routes:
      #     - network: 0.0.0.0/0
      #       gateway: 172.16.11.254
      #   mtu: 1500
      - interface: eth1
        dhcp: false
        addresses:
          - 172.16.11.15/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.15/24
            mtu: 1500
    nodeLabels: *workerLabels

  # M920X
  - hostname: k8s-w3.${clusterDNSSuffix}
    ipAddress: 172.16.11.16
    installDisk: /dev/nvme1n1
    controlPlane: false
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: ec:0d:9a:00:27:90
      #       - hardwareAddr: ec:0d:9a:00:27:91
      #   dhcp: false
      #   addresses:
      #     - 172.16.11.16/24
      #   routes:
      #     - network: 0.0.0.0/0
      #       gateway: 172.16.11.254
      #   mtu: 1500
      - interface: eth1
        dhcp: false
        addresses:
          - 172.16.11.16/24
        routes:
          - network: 0.0.0.0/0
            gateway: 172.16.11.254
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.16/24
            mtu: 1500
    nodeLabels: *workerLabels

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
        - talos.logging.kernel=udp://${vectorAggregatorAddr}:${talosKernelLogPort}/
      systemExtensions:
        officialExtensions:
          - siderolabs/nut-client
          - siderolabs/intel-ucode
          - siderolabs/i915-ucode

  patches:
    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - 172.16.11.0/24

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - - talos-system

    # Enable logging
    - &loggingPatch |-
      machine:
        logging:
          destinations:
            - endpoint: udp://vector.${clusterDNSSuffix}:${talosServiceLogPort}
              format: json_lines

    # Disable search domain everywhere
    - &disableSearchDomainPatch |-
      machine:
        network:
          disableSearchDomain: true

    # Force nameserver
    - &nameServerPatch |-
      machine:
        network:
          nameservers:
            - 10.255.253.1

    # Configure NTP
    - &ntpServerPatch |-
      machine:
        time:
          disabled: false
          servers:
            - time.google.com
            - time.cloudflare.com

    # Enable cluster discovery
    - &discoveryPatch |-
      cluster:
        discovery:
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: true

    # Enable KubePrism
    - &kubePrismPatch |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # Configure kubelet
    - &kubeletPatch |-
      machine:
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: true
          extraConfig:
            maxPods: 150
          nodeIP:
            validSubnets:
              - 172.16.11.0/24

    # Custom sysctl settings
    - &sysctlPatch |-
      machine:
        sysctls:
          fs.inotify.max_user_watches: 1048576
          fs.inotify.max_user_instances: 8192
          kernel.randomize_va_space: 0
          net.core.netdev_max_backlog: 30000
          net.core.rmem_max: 67108864
          net.core.wmem_max: 67108864
          net.ipv4.tcp_rmem: 4096 87380 33554432
          net.ipv4.tcp_wmem: 4096 65536 33554432
          net.ipv4.tcp_tw_reuse: 1
          net.ipv4.tcp_window_scaling: 1

    # Configure containerd
    - &containerdPatch |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true

    # Configure nut client
    - |-
      machine:
        files:
          - op: create
            path: /var/etc/nut/upsmon.conf
            permissions: 0o600
            content: |
              MONITOR ${upsmonMasterHost} 1 ${upsmonMasterUser} ${upsmonMasterPass} slave
              SHUTDOWNCMD "/sbin/poweroff"

    # Static host entries
    - &staticHostEntriesPatch |-
      machine:
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.${clusterDNSSuffix}

    # Configure pull through cache
    - &pullRegistryPatch |-
      machine:
        registries:
          mirrors:
            docker.io:
              endpoints:
                - https://registry.monosense.io/v2/docker.io
              overridePath: true
            ghcr.io:
              endpoints:
                - https://registry.monosense.io/v2/ghcr.io
              overridePath: true
            quay.io:
              endpoints:
                - https://registry.monosense.io/v2/quay.io
              overridePath: true
            gcr.io:
              endpoints:
                - https://registry.monosense.io/v2/gcr.io
              overridePath: true
            registry.k8s.io:
              endpoints:
                - https://registry.monosense.io/v2/registry.k8s.io
              overridePath: true
            public.ecr.aws:
              endpoints:
                - https://registry.monosense.io/v2/public.ecr.aws
              overridePath: true

worker:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
        - talos.logging.kernel=udp://${vectorAggregatorAddr}:${talosKernelLogPort}/
      systemExtensions:
        officialExtensions:
          - siderolabs/nut-client
          - siderolabs/intel-ucode
          - siderolabs/i915-ucode
          - siderolabs/iscsi-tools

  patches:
    # Configure nut client
    - |-
      machine:
        files:
          - op: create
            path: /var/etc/nut/upsmon.conf
            permissions: 0o600
            content: |
              MONITOR ${upsmonWorkerHost} 1 ${upsmonWorkerUser} ${upsmonWorkerPass} slave
              SHUTDOWNCMD "/sbin/poweroff"

    - *loggingPatch
    - *disableSearchDomainPatch
    - *nameServerPatch
    - *ntpServerPatch
    - *discoveryPatch
    - *kubePrismPatch
    - *kubeletPatch
    - *sysctlPatch
    - *containerdPatch
    - *pullRegistryPatch
    - *staticHostEntriesPatch
