---
clusterName: ${clusterName}
endpoint: "https://${clusterName}.${domainName}:6443"

talosVersion: v1.5.5
kubernetesVersion: 1.28.3

# Image URL rendered on https://factory.talos.dev
# customization:
#     extraKernelArgs:
#         - net.ifnames=0
#     systemExtensions:
#         officialExtensions:
#             - siderolabs/i915-ucode
#             - siderolabs/intel-ucode
# talosImageURL: factory.talos.dev/installer/22b1d04da881ef7c57edb0f24d1f3ba2c78a8e22cbe3fa9af4f42d487b2863f7

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - ${clusterName}.${domainName}

nodes:
  # Thinkcentre M910q Core i7 7700t, 32GB RAM, 256GB SSD, 1x1Gbps NIC
  - hostname: k8s-m0.${domainName}
    ipAddress: 172.16.11.10
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
  # nodeLabels: &masterLabels
  #   topology.kubernetes.io/region: ${clusterName}
  #   topology.kubernetes.io/zone: k8s-master
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/tripranata/installer-master:v1.5.5

  - hostname: k8s-m1.${domainName}
    ipAddress: 172.16.11.11
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
  # nodeLabels: *masterLabels
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/tripranata/installer-master:v1.5.5


  - hostname: k8s-m2.${domainName}
    ipAddress: 172.16.11.12
    installDisk: /dev/sda
    controlPlane: true
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
  # nodeLabels: *masterLabels
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/tripranata/installer-master:v1.5.5

  ### Worker Node
  ### Mixed Thinkcentre M720q & M910x
  ### Core i7 8700t, 64GB RAM, 240GB SSD/512GB NVME (OS), 1x1TB NVME (CEPH), 2x10Gbps Mellanox ConnectX-3 Pro EN, 1x1Gbps NIC
  # M720Q
  - hostname: k8s-w0.${domainName}
    ipAddress: 172.16.11.13
    installDisk: /dev/sda
    controlPlane: false
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:79:67:75:95
      #       - hardwareAddr: e4:1d:79:67:75:96
      - interface: eth1
        dhcp: true
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.13/24
            mtu: 1500
    # nodeLabels: &workerLabels
    #   node-role.kubernetes.io/worker: worker
    #   topology.kubernetes.io/region: ${clusterName}
    #   topology.kubernetes.io/zone: k8s-worker
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/trosvald/installer-worker:v1.5.5

  # M720Q
  - hostname: k8s-w1.${domainName}
    ipAddress: 172.16.11.14
    installDisk: /dev/sda
    controlPlane: false
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:85:75:d8:73
      #       - hardwareAddr: e4:1d:85:75:d8:74
      - interface: eth1
        dhcp: true
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.14/24
            mtu: 1500
    # nodeLabels: *workerLabels
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/trosvald/installer-worker:v1.5.5

  # M720Q
  - hostname: k8s-w2.${domainName}
    ipAddress: 172.16.11.15
    installDisk: /dev/sda
    controlPlane: false
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: e4:1d:7a:67:a5:d4
      #       - hardwareAddr: e4:1d:7a:67:a5:d5
      - interface: eth1
        dhcp: true
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.15/24
            mtu: 1500
    # nodeLabels: *workerLabels
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/trosvald/installer-worker:v1.5.5

  # M920X
  - hostname: k8s-w3.${domainName}
    ipAddress: 172.16.11.16
    installDisk: /dev/nvme1n1
    controlPlane: false
    disableSearchDomain: true
    nameservers:
      - 172.16.16.5
    networkInterfaces:
      - interface: eth0
        ignore: true
      # - interface: bond0
      #   bond:
      #     mode: active-backup
      #     miimon: 100
      #     deviceSelectors:
      #       - hardwareAddr: ec:0d:9a:00:27:90
      #       - hardwareAddr: ec:0d:9a:00:27:91
      #   dhcp: true
      #   mtu: 1500
      - interface: eth1
        dhcp: true
        mtu: 1500
        vlans:
          - vlanId: 1613
            dhcp: false
            addresses:
              - 172.16.13.16/24
            mtu: 1500
    # nodeLabels: *workerLabels
    patches:
      - |-
        machine:
          install:
            image: ghcr.io/trosvald/installer-worker:v1.5.5
# patches:
#   - |-
#     machine:
#       install:
#         image: ghcr.io/trosvald/installer-worker:v1.5.5

controlPlane:
  patches:
    - |-
      cluster:
        proxy:
          disabled: true
        etcd:
          advertisedSubnets:
            - 172.16.11.0/24
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:etcd:backup
            allowedKubernetesNamespaces:
              - talos-system
        install:
          extraKernelArgs:
            - net.ifnames=0
            - talos.logging.kernel=udp://${vectorAggregatorAddr}:6001/
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
          - op: create
            path: /var/etc/nut/upsmon.conf
            content: |-
              MONITOR ${upsmonMasterHost} 1 ${upsmonMasterUser} ${upsmonMasterPass} slave
              SHUTDOWNCMD "/sbin/poweroff"
            permissions: 0o600
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
        logging:
          destinations:
            - endpoint: udp://${vectorAggregatorAddr}:6002/
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.${domainName}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 172.16.10.254
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

worker:
  patches:
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
          - content: |-
              MONITOR ${upsmonWorkerHost} 1 ${upsmonWorkerUser} ${upsmonWorkerPass} slave
              SHUTDOWNCMD "/sbin/poweroff"
            path: /var/etc/nut/upsmon.conf
            permissions: 0o600
            op: create
        kubelet:
          extraArgs:
            feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,NewVolumeManagerReconstruction=false
            rotate-server-certificates: "true"
        install:
          extraKernelArgs:
            - net.ifnames=0
            - talos.logging.kernel=udp://${vectorAggregatorAddr}:6001/
        logging:
          destinations:
            - endpoint: udp://${vectorAggregatorAddr}:6002/
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.${domainName}
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - 172.16.10.254
