clusterName: ENC[AES256_GCM,data:PbU6teR18PLV,iv:CB+VmyM1k6Qv0xDzcWOy39Ovvhld/gfuEWQ3g8A0DdI=,tag:VcIKFYACbLNSwgNUMIJdvw==,type:str]
domainName: ENC[AES256_GCM,data:3cFkrYapKFsGg/H5,iv:tjY7zn8SJxfRfCx9PMeVXONvllRF6khXbPNmbjsWIoI=,tag:LAms7tRHqNVzdvzkRtj9KA==,type:str]
clusterEndpointIP: ENC[AES256_GCM,data:jmBtFo7sKiWSyuI=,iv:z1w0my5eGhy9AH0Tt+nOZWdcc7j5EugW73NwmrXgZVQ=,tag:cTcQc/f+f2OqKuEj4wbjhw==,type:str]
upsmonMasterHost: ENC[AES256_GCM,data:j6lgLjOF11xypJiUidHmSzzy/TL7nQpYboqQhLcRhCut,iv:y8evUk26jY9KcZNIK9GhthczYiw980qPFKkOPy3ap0o=,tag:zBIqkrCe+4UMCfx68CyVJg==,type:str]
upsmonMasterUser: ENC[AES256_GCM,data:+qEXFHbEUBoV,iv:HPaIiAhfNZdcvrGCIo4esXO4rKzm1nJG48EEw+fONTA=,tag:BB3/jWjTw+zDWGFBpjvT3g==,type:str]
upsmonMasterPass: ENC[AES256_GCM,data:G3I3F+PjQ1bhVQ==,iv:W314AF30QaGYUuNI+aCeoTObKGsxmFvUQ9Y7sKm9HPI=,tag:qtJEP92yGZ8jc9KdTUiWNA==,type:str]
upsmonWorkerHost: ENC[AES256_GCM,data:6sZtPhH8dXv+0jQ9Z9AhmNkMttLXCIww87D9cX71dAmS,iv:SkzsyKUzMYM9/mY3eKgdW6pq2mK6AYX+UZEQw/HUa38=,tag:FTlY+a4TbTmK459mFJACHg==,type:str]
upsmonWorkerUser: ENC[AES256_GCM,data:0jY+v+zTucmr,iv:2nLdw7KP4sMLRCg2C3OmofFQWkmnu2ehQTzM9dHCVo0=,tag:JIAX0M/rX1oZLLuExcV7Zw==,type:str]
upsmonWorkerPass: ENC[AES256_GCM,data:PGsPSzHbyxOj4Q==,iv:XBy0FqAtZ0aDO7oz4TtgE3IuAFONUIpAXta3pZkEDxM=,tag:eEusDYFIj+t10uOLROlFUw==,type:str]
vectorAggregatorAddr: ENC[AES256_GCM,data:FObqHb0sTH33eg==,iv:8jT2zHCx4f5tZ5OyBj+XUOBOxX0eO2W2H14gw543UZg=,tag:NbRrbESm/XkOEqA8AoIiaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcjJCRHg3MzdrZDlmNlBj
            aFZKV3BwTXZIM1JJTXdyZGpKQ2l6Y05adTJ3CkRGZUFoRkZLT2NLTGJPd1p3KzRC
            RzcyVTIxK1pNd2RMc0Zvc25TNmRwamcKLS0tIDNwclExZ2RHTmlJN0JTa1YrQy9t
            WVlDVnZQcnlKSE1jci96azRyR21pcTQKzIx2Tw6Nc+9FToNLUVaSLxqrEiXhQRY7
            kDovdmm+p7ZMeylfnTqjprmfhHq36qpHPX+W5xkIRQCu+Y5FR14tMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-13T09:18:02Z"
    mac: ENC[AES256_GCM,data:e2pmcvljlw+LPo6A33SFnrgg9veJCga1oy4hYzFR/zfiMYkp0xAKMrwPGhRZB+vjSljnbR/0xWx5rpRCl6jdBauMSQGSjySK9KKLhDvVG/clmMondEUv/GiRrlmUtqUfmX3HVz+cJDLhYVyxZDwzbmCurPKpKpnS7tjLL9PBQGI=,iv:KYe8SPI+vqEqZ5hFs1gNviGPSXbnclpwnVDEYlSAzxo=,tag:Za63MZsyRcTFeAFoMpcosQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.8.1
