---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-kube-prometheus-stack
  namespace: flux-system
spec:
  path: ./kubernetes/apps/monitor/kube-prometheus-stack/app
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    # TODO : Change this to ceph rook
    - name: storage-democratic-csi-iscsi
    - name: security-external-secrets