---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-piped
  namespace: flux-system
spec:
  path: ./kubernetes/apps/selfhosted/piped/app
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-crunchy-postgres-operator
