---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-grafana-db
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/grafana/db"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false # no flux ks dependents
  dependsOn:
    - name: production-rook-ceph-cluster
    - name: production-external-secrets-stores

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false # no flux ks dependents
  dependsOn:
    - name: production-grafana-db
