---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-cdn
  namespace: flux-system
spec:
  path: ./kubernetes/apps/network/cdn/app
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: home-cluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname cdn
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: cdn.monosense.io
