---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: esphome-src
spec:
  sourcePVC: esphome-config
  trigger:
    schedule: "15 */8 * * *"
  restic:
    copyMethod: Snapshot
    repository: esphome-restic-secret
    cacheStorageClassName: ceph-block
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    pruneIntervalDays: 7
    retain:
      daily: 7
      within: 3d
