---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-actions-runner-controller
  namespace: flux-system
spec:
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller
  interval: 10m
  path: "./kubernetes/apps/dev/actions-runner-controller/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: production-external-secrets-stores

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-actions-runner-controller-runners
  namespace: flux-system
spec:
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: actions-runner-controller-runners
  interval: 10m
  path: "./kubernetes/apps/dev/actions-runner-controller/runners"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  dependsOn:
    - name: production-actions-runner-controller
    - name: production-rook-ceph-cluster
