---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/system/volsync/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-storage-democratic-csi-nfs
    - name: cluster-apps-snapshot-controller
  wait: true
  timeout: 2m
