---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  namespace: network
spec:
  endpoints:
    - dnsName: ingress-ext.monosense.io
      recordType: CNAME
      targets: ["853db751-b964-4d93-8b17-fb2e03941c91.cfargotunnel.com"]
