---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-cluster
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: kafka-cluster
  endpoints:
    - port: 9404
      interval: 30s
      path: /
