data_dir: /vector-data-dir

api:
  enabled: false

# Sources
sources:
  journald_source:
    type: journald
    journal_directory: /var/log/journal
  kubernetes_logs:
    type: kubernetes_logs
    use_apiserver_cache: true
    pod_annotation_fields:
      container_image: container_image
      container_name: container_name
      pod_annotations: pod_annotations
      pod_labels: pod_labels
      pod_name: pod_name

# Sinks
sinks:
  journald_sink:
    type: vector
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6004
    inputs:
      - journald_source
  kubernetes_sink:
    type: vector
    compression: true
    inputs:
      - kubernetes_logs
    address: "vector-aggregator.monitoring.svc.cluster.local:6000"
    version: "2"
