---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-intel-device-plugins-operator
  namespace: flux-system
spec:
  path: "./kubernetes/apps/system/intel-device-plugins/operator"
  sourceRef:
    kind: GitRepository
    name: home-cluster
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: production-cert-manager
    - name: production-node-feature-discovery-rules
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-intel-device-plugins-gpu
  namespace: flux-system
spec:
  path: "./kubernetes/apps/system/intel-device-plugins/gpu"
  sourceRef:
    kind: GitRepository
    name: home-cluster
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: production-intel-device-plugins-operator
