---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "monosense-io"
  namespace: network
spec:
  secretName: "monosense-io-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "monosense.io"
  dnsNames:
    - "monosense.io"
    - "*.monosense.io"
