---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "page-monosense-io"
  namespace: network
spec:
  secretName: "page-monosense-io-tls"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: default,dev
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "page.monosense.io"
  dnsNames:
    - "page.monosense.io"
    - "*.page.monosense.io"
