# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-paperless-redis
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: "./kubernetes/apps/selfhosted/paperless/redis"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-cluster
#   wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/selfhosted/paperless/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  dependsOn:
    # - name: cluster-apps-paperless-redis
    - name: cluster-apps-redis
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
    - name: cluster-apps-external-secrets-stores
