---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-media
spec:
  storageClassName: syno-nfs-immich
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${CONFIG_SYNO_IP}"
    path: /volume1/k8s/immich
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: syno-nfs-immich
  resources:
    requests:
      storage: 1Mi
  volumeName: immich-media