---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-home-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 30m

  values:
    runnerScaleSetName: arc-runner-set-home-cluster

    githubConfigUrl: https://github.com/trosvald/home-cluster

    minRunners: 1
    maxRunners: 5

    containerMode:
      type: "dind"

    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/github-actions-runner:rolling@sha256:e24bb8f3d809b706cd740c47f688dcecbf3886f3ac819d61b7b1f5644a2f091d
            command: ["/home/runner/run.sh"]
            volumeMounts:
              - name: cache-volume
                mountPath: /cache
        volumes:
          - name: cache-volume
            persistentVolumeClaim:
              claimName: actions-runner-controller-cache

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
