---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datahub-user
  namespace: datahub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: datahub-user
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:

        datahub-user: "{{ .KAFKA__DATAHUB_PASSWORD }}"


  dataFrom:
    - find:
        path: KAFKA__
