---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datahub
resources:
  - ./externalsecret.yaml
  - ./kafka-cluster.yaml
  - ./kafka-user.yaml
  - ./topic.yaml

patches:
  - target:
      version: v1
      kind: Service
      name: kafka-cluster-kafka-external-1
    path: ./patches/kafka-cluster-kafka-external-1.yaml
