---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-nfs-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-nfs
          httpConnection:
            protocol: http
            host: "san.monosense.io"
            port: "80"
            apiKey: "eyJhIjoiZWNhMDgzM2Y2MDhiNTc0NWFmMDMwMzA3YTk5YmRiYjQiLCJ0IjoiNGJmZTIxM2EtZDA1ZC00YmFiLWE1NjgtNzg0ZDRkOWJlNGRkIiwicyI6IllUTmxaR1EwWTJZdFlUTXlaQzAwTVRRNUxXRmxZVFV0WWpjNE9HUTNNak0yWWpGaiJ9"
            allowInsecure: true
          sshConnection:
            host: "san.monosense.io"
            port: "22"
            username: "root"
            privateKey: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
              QyNTUxOQAAACCQMhTelJII+8oRqQY71ZHeDd6jQSKeKu+/H4KktgARyQAAAJiUlWUZlJVl
              GQAAAAtzc2gtZWQyNTUxOQAAACCQMhTelJII+8oRqQY71ZHeDd6jQSKeKu+/H4KktgARyQ
              AAAEBGrk9+QlY2rXWUkWzkA3jUDHx0YsbtSw8rhdv3dy7GOJAyFN6Ukgj7yhGpBjvVkd4N
              3qNBIp4q778fgqS2ABHJAAAAFXJvb3RAc2FuLm1vbm9zZW5zZS5pbw==
              -----END OPENSSH PRIVATE KEY-----
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: raid-z1/k8s/nfs/vols
            detachedSnapshotsDatasetParentName: raid-z1/k8s/nfs/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareCommentTemplate: "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            shareHost: "san.monosense.io"
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: ["172.16.11.0/24"]
            shareMaprootUser: root
            shareMaprootGroup: root
            shareMapallUser: ""
            shareMapallGroup: ""
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi