---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.37.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
      interval: 5m
  values:
    logVolume: co-config-volume
    logConfigMap: strimzi-cluster-operator
    logConfiguration: ""
    logLevel: ${env:STRIMZI_LOG_LEVEL:-INFO}
    fullReconciliationIntervalMs: 120000
    operationTimeoutMs: 300000
    kubernetesServiceDnsDomain: cluster.local # TODO: K8S service domain
    featureGates: ""
    tmpDirSizeLimit: 1Mi
    dashboards:
      enabled: false
      namespace: ~
      label: grafana_dashboard # this is the default value from the grafana chart
      labelValue: "1" # this is the default value from the grafana chart
      annotations: {}
      extraLabels: {}
    resources:
      limits:
        memory: 384Mi
        # cpu: 1000m
      requests:
        memory: 384Mi
        cpu: 200m
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
