# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AyO16U/KM2ccuQ2X,iv:xACc8PziCPumYRChhhDrisbsvGiY6Zg6FZHtHwzMYyg=,tag:Mt16RAH9CqIcvGy3xZPTzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua2V6a2hLZlIvc0tUY2ZN
            Z1dLNHlBeHAwTUJFMFdkQlo1UEgvQS9Bb1JVCmFZbndONUJTVGJ5MHNUTU9KQzlu
            bHVRbllibFd2Z0M5T04yWk1VTVdYdmcKLS0tIE5vb3lqMVdlRVV6dThKWVdOWmFh
            RDZtYW5FaEdVREM5QUI3TTBJOS9mMVEKuXrh1HigIoMg4RyDOKOKFnpQ2X3iibnk
            EK3fYLhRicQ9Eu1Goqqph93ZlfZbQM0AEERjptwhz/kk+Ve5N2tpzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-16T06:30:53Z"
    mac: ENC[AES256_GCM,data:iXvkGD5TcStoazUbKPF17ep+9AAyfssOXzxf01hB4e+Ldryl/qKHMKLnZ05rZWz13GW2LKVCvOHPbjGgHotaJeWwYecZyotu2nV/myJT2JtOn75LVyBWmsaypq7DpjJs5EIyEGdyxd7kKadhAZm6CrU0xFQkyO7WEMhHi6RLJKU=,iv:ScjxXccsStrmENmRWNERSwI4CYyVAExkT/07a5pj3D4=,tag:nNnEr1u0bNYRrKb0iNtQ2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
