# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:0HCiwa9wzpsPzVnz,iv:bqTEdRNNLeyFeXTYfkq94gBXyYJH9rocuvL8NyaArJg=,tag:d+MszV7u98rNszYLBYi7Sw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:Amt+7I4qcbLg2dwRLrG2RgwhtgdFMHPQpS4bxEd8eGTSVUnSeb7dZR52EjbguQ==,iv:B4gOeVKeFdP/Y2QGeU4QHI7aVncMQ1EoeNBeEpN1eek=,tag:pGCq4ctRSAzz/fvB8fsDjg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:FjZsJKgAQye8,iv:RZLy91za6LDiFUCHNteIU5k6G1xZUlpDxVRn3wvMTSQ=,tag:mEKVCrm+EOc2AIgtBRitYg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzak9FS2M3bnhlSzVBL1Fp
            U3VzUnVHVXdxTVpVYWxlQzJab25HUzBabDNjCkJuVDZid3RSdlpWT1l5V3Z0VEhx
            UlRWdjBsSzJHNHpxWVc5L2FxQnZRU1UKLS0tIEtoNUE5cGdaRnc0ak9kc0IyWDRv
            bzJZa2Z6RE5sdGUwZ1Fpd052aFZudkUKjY43KObgbsydvtHBqYNN5oYO/XQ1/jhk
            s2tALDgQPygCPyHmFqe9c00K9HMT51Sz3CjWaHdjAeD3dCItJohISw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-18T11:14:04Z"
    mac: ENC[AES256_GCM,data:l9MydV2CUO1HYe7NqBvBQqh7iFDB7WV4OuFwkZxM+pKojVnkEdk9/du9yqVk06var3ibzCxJu1Yuzm1AAGjuqyMxX90D5GLYZcG+v24aJ4gtOG/O8a7p/pGFwNx/QibWUHJbeEcQ2DfgtySUMdyyxbRY7tpRL4D/76NrHvQabwg=,iv:416H0g/rMVqHA4zSdnrm/yMfGEKBhisXW9SUMpyviUw=,tag:GrONJtGLUcZKgohplMwGJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
