# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HzNrBpo14kJYMNWT,iv:eMx+DWREwsI6gm9c3Z/fOIUS9KiX6P1Qqj+uTKpqlBs=,tag:Yx5XDnxHp4/v2OHB61X+iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeGFoREpUNXI5VGExLzdB
            YjhFSzJKZmozZU5RQlhNS1JUZHYwdFROblZBClVNeTUrdllvR3Z4VnlqanhnbndN
            cnNYZXZDT3ZZajYwaWhQME53STZGODgKLS0tIE4vdlFOTVYrbDdUZWNVYkk1RzVn
            WTVXN0FMOFQvVDNkQllkZmtublRydlEKCf7WehJHGzETWeucdV9vuNsNqI9G4hNH
            qr+7Ab3jB/xEM6riHPxJdrnjMDZBy0/SRTGuA6OETQT1KutZ8UxnJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-13T11:08:56Z"
    mac: ENC[AES256_GCM,data:EeFBSFoDw+TUG404kE09sxUnY5kMHX9sbhZzTyuVvNyWYgkpLDCOz1aOMA1ZWMZQdsrr5lEuB2wuUcQpYBLOymndLIYMcGYEzHGmpl69Y/uBXVsBgjbaNtxNlJ6ptovYZy/JSikulieeKW6bNX2sI0ulIvHalxQIjcQ+M62wkhY=,iv:35L/yq++yjh0XD2kUOEDBc/VfMGKK8i/zGDdjpBelBI=,tag:zaCEo55JOH3PbfXGb57IEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
