---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name talos-s3-secret
  namespace: talos-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_REGION: "{{ .minio_region }}"
        AWS_ACCESS_KEY_ID: "{{ .minio_talos_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_talos_secret_key }}"
        CUSTOM_S3_ENDPOINT: https://s3.${SECRET_DOMAIN}:9000
        BUCKET: talos
        CLUSTER_NAME: cluster-0
        S3_PREFIX: backups
        AGE_X25519_PUBLIC_KEY: "{{ .talos_age_public_key }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: talos
