---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./volsync
  - ./pvc.yaml
  - ./pvc-nfs.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/part-of: paperless
