---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-volsync
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/volsync/app
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: true
  dependsOn:
    - name: storage-democratic-csi-iscsi
    - name: storage-snapshot-controller
  interval: 30m
  retryInterval: 1m
  timeout: 5m