---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-secrets
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitlab-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GITLAB_ROOT_PASSWORD: "{{ .gitlab_root_password }}"
        GITLAB_SMTP_HOST: "{{ .zohomail_smtp_host }}"
        GITLAB_SMTP_PORT: "{{ .zohomail_smtp_port }}"
        GITLAB_SMTP_USER: "{{ .zohomail_email_address }}"
        GITLAB_SMTP_PASSWORD: "{{ .zohomail_smtp_password }}"
  dataFrom:
    - extract:
        key: gitlab
    - extract:
        key: zohomail
