---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: dev
spec:
  releaseName: gitlab
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: 7.6.0
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      edition: ee

      initialRootPassword:
        secret: &secret gitlab-secrets
        key: GITLAB_ROOT_PASSWORD

      hosts:
        domain: &domain monosense.io
        gitlab:
          name: gitlab.monosense.io
          https: true
        pages:
          name: pages.monosense.io
          https: true
        registry:
          name: gitlab-registry.monosense.io
          https: true
        minio:
          name: minio.monosense.io
          https: true

      ingress:
        class: external-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.monosense.io
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        configureCertmanager: false
        tls:
          enabled: true
          secretName: monosense-io-tls

      certmanager:
        installCRDs: false
        install: false
        rbac:
          create: false

      kas:
        enabled: false

      pages:
        enabled: true

      minio:
        enabled: true
        persistence:
          storageClass: truenas-iscsi
          size: 80Gi

      appConfig:
        omniauth:
          enabled: true
          allowSingleSignOn: ['saml']
          syncEmailFromProvider: 'saml'
          syncProfileFromProvider: ['saml']
          syncProfileAttributes: ['email']
          #autoSignInWithProvider: 'saml'
          blockAutoCreatedUsers: false
          autoLinkSamlUser: true
          providers:
            - secret: gitlab-authentik-saml
      #   object_stor:
      #     enabled: true
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   lfs:
      #     enabled: true
      #     bucket: gitlab-lfs
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   artifacts:
      #     enabled: true
      #     bucket: gitlab-artifacts
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   uploads:
      #     enabled: true
      #     bucket: gitlab-uploads
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   packages:
      #     enabled: true
      #     bucket: gitlab-packages
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   externalDiffs:
      #     enabled: true
      #     bucket: gitlab-mr-diffs
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   terraformState:
      #     enabled: true
      #     bucket: gitlab-terraform-state
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   ciSecureFiles:
      #     enabled: true
      #     bucket: gitlab-ci-secure-files
      #     connection:
      #       secret: gitlab-rails-s3-secrets
      #   dependencyProxy:
      #     enabled: true
      #     bucket: gitlab-dependency-proxy
      #     connection:
      #       secret: gitlab-rails-s3-secrets

        backups:
          bucket: gitlab-backup
          tmpBucket: gitlab-tmp

      email:
        display_name: GitLab
        from: info@monosense.io
        reply_to: "no_reply@monosense.io"

      smtp:
        enabled: true
        domain: *domain
        starttls_auto: true
        password:
          secret: *secret
          key: GITLAB_SMTP_PASSWORD

      praefect:
        enabled: false
        virtualStorages:
          - name: default
            gitalyReplicas: 3
            maxUnavailable: 1

      # Database
      psql:
        password:
          useSecret: true
          secret: gitlab-pguser-gitlab
          key: password

      # redis:
      #   host: redis.database.svc.cluster.local
      #   serviceName: redis-master
      #   port: 6379
      #   sentinels:
      #     - host: redis-node-0.redis-headless.database.svc.cluster.local
      #       port: 26379
      #     - host: redis-node-1.redis-headless.database.svc.cluster.local
      #       port: 26379
      #     - host: redis-node-2.redis-headless.database.svc.cluster.local
      #       port: 26379
      #   auth:
      #     enabled: false
    registry:
      enabled: true
      storage:
        secret: gitlab-registry-s3-secrets
        key: config

    gitlab:
      gitaly:
        persistence:
          storageClass: truenas-iscsi
          size: 200Gi
        resources:
          requests:
            cpu: 80m
            memory: 340M
          limits:
            cpu: 1800m

      webservice:
        minReplicas: 1
        maxReplicas: 1
        workerProcesses: 2
        resources:
          limits:
            memory: 3.0Gi # roughly, 1.5GB/worker
          requests:
            cpu: "1.1" # requests.cpu <= workerProcesses
            memory: 2.50Gi # roughly, 1.25GB/worker

      sidekiq:
        minReplicas: 1
        maxReplicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 600M

      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1

      gitlab-pages:
        # The default requests are massive for a static server
        resources:
          requests:
            cpu: 50m
            memory: 50Mi

      toolbox:
        backups:
          objectStorage:
            config:
              secret: gitlab-backup-s3-secrets
              key: config

    # Disable things we handle by ourselves
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    postgresql:
      install: false
    redis:
      install: true
    prometheus:
      install: false
    grafana:
      enabled: false

    gitlab-runner:
      runners:
        config: |
          concurrent = 10
          [[runners]]
            [runners.kubernetes]
              cpu_request = "500m"
              cpu_limit = "1"
              memory_request = "200Mi"
              memory_limit = "1Gi"
              service_cpu_request = "100m"
              privileged = true
              service_cpu_limit = "1"
              service_memory_request = "50Mi"
              service_memory_limit = "1Gi"
              helper_cpu_request = "5m"
              helper_cpu_limit = "500m"
              helper_memory_request = "50Mi"
              helper_memory_limit = "200Mi"

  valuesFrom:
    # DATABASE
    - kind: Secret
      name: gitlab-pguser-gitlab
      valuesKey: host
      targetPath: global.psql.host
    - kind: Secret
      name: gitlab-pguser-gitlab
      valuesKey: dbname
      targetPath: global.psql.database
    - kind: Secret
      name: gitlab-pguser-gitlab
      valuesKey: user
      targetPath: global.psql.username

    # STMP
    - kind: Secret
      name: *secret
      valuesKey: GITLAB_SMTP_HOST
      targetPath: global.smtp.address
    - kind: Secret
      name: *secret
      valuesKey: GITLAB_SMTP_USER
      targetPath: global.smtp.user_name
    - kind: Secret
      name: *secret
      valuesKey: GITLAB_SMTP_PORT
      targetPath: global.smtp.port
