---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  # - ./helmrelease.yaml
  - ./externalsecret.yaml
  - ./postgresCluster.yaml
commonLabels:
  app.kubernetes.io/name: gitlab
  app.kubernetes.io/instance: gitlab
