---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: loki
        S3_BUCKET_HOST: "{{ .minio_server }}"
        S3_BUCKET_REGION: "{{ .minio_region }}"
        S3_ACCESS_KEY: "{{ .minio_user }}"
        S3_SECRET_KEY: "{{ .minio_password }}"
  dataFrom:
    - extract:
        key: minio
