---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-democratic-csi-nfs
  namespace: flux-system
spec:
  path: "./kubernetes/apps/storage/democratic-csi/nfs"
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  interval: 10m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-democratic-csi-iscsi
  namespace: flux-system
spec:
  path: "./kubernetes/apps/storage/democratic-csi/iscsi"
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  interval: 10m
  retryInterval: 1m
  timeout: 5m