apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:zgfXDWnOzm7Z8I0QI2ZmkN6yZHBVMwi2cnHf6QWv50tZ7JSjbZl8bKgMGDbfAys/wridcQOL5WfOWG9aLIMqDLPKCk5S3UP9UouBjy+CVdMqEdOqOe9oxpwzbNy8Q5Nu7ZtWtaXOHhQND/uaGcHUmQrRLT9x1rRHu/CM6nMpD2JrYTqrj1pFJEFYZNClGtwsSf/6UxdWXqKnyJib4uKx2F6bI5e33I2VdFn2xLVgZ9mygbixVH3dZTVL88wW+qkzZsCMPG6e2KzqVRX+ZDV05y5HHCmta2gorRJdKnwRXxkyjHtIb+goqpDjWjf0AMfXILX6DqN8PA564p1W/fqCS5rUF+76Q7BROq4Kih/IKQkQjOQ1xbvb104okGDIfkWWRaAIpi5MkEr14M6cYL5I45F4YVnqV2fJLgMIF9v0SBo33ievDmKNmh4f5q4QWw9VQdJESwAhd8IJmpo4X2zkSJE5cVaJwuP91TZLHJkwqp6tMQUM2WZtzUt7w5hwgn/Mx/tR/GH7uGosqcgcuzIpC91Ps3LCDAN0PuZRtQEARa5anm4Gt5FYQKQZiXKhj+AXjl7dw5a8P8mxeWQaitFnt3S4DHQg+zINkGpHoIzmuSikH45vWM3b5VxFQcJhzVnaoKdkCnFjnVx1rVnerpfxxHVpSv82LmrhKobSW8KWAqefJp8z7TlYBqQmjqFKmrutFQj3OUL88azmGQ5CEKy2G6k6mJebFMcy2ULabAcCSF+iP7ljMPt6BrkBsMjUsjsp1fIxR7XgfKTjHPT82gETLCJgVAakg1T8VSuTPaHUZx6+QFqU3IvXdxOKrIzE3oy13vp554zSziX1xNmjMl2KtFQ9VV68aiLlZh/9JzqI7oEwtvLsb2nqzddc6tyYDQNkPekIpPAsy+hIxAZpQ2GkiOWyQNQhXnPKCcMnB/QrAdLDO3EvDLKsb+uQWamd25AhXujRn5GWC79fvaikPemaTNREms8n8IkOEJz5flKQYB7zhCjFec645tZs9Nx9Mz8BSLKPvEVAW9eP1Pj88OdgeSXc0B3QM99+Fkpl9mEr/C0jQ3570YZmhrvwjcQiiXYoePWpIwu0cBoKwsR27z/B4jUqVrNjCnXC9bZW/Av6NE9/EeYquYmqGClB+X0=,iv:dLzhYmY8TbWsfkEdTOI4rNXbpmU6WyU3hgQe8AF1iZc=,tag:s8fIgeLffahC7l8cCw05og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZXBqZGtwQzBDQ09yUExF
            L3hEZHVVWTlWYzRUWHFrMW1rU1BZR3VMa0FZCnM4NlU4RkhOOUl4dmd5dnNDdVl4
            bW1reWc2MGVHbW5qZndaRHZUNWVaUmMKLS0tIHJlMVRrdHFEVTIzTjdPRlZpRVpI
            WnQ5N1RYZWxLUnZ2Qko3NWZCcUloN1UKiqfGQVlu/I1atxGKOdLGMqaLUgZW0lRx
            T4W0BvP/R5xXSMrz0JYBcKNS4y4dkmZnj6nMfA88LrRBCZPPxjKnOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-13T04:19:23Z"
    mac: ENC[AES256_GCM,data:oh7zuIQuJ/chqdMAEgvIzzbQMH19ieSyDbWodk+UhnR9KBVnjWvkUbYLkSOtSkeo8RC+Q91TTVWueeThPdLXftx7kEh0wSk2VNmK2e79BOSW8fBoKpHVU0jQOKj8Za7hJMUCJYnGqhV+vLf/WPKYORU/y5wFifv3d9a/xOlUauA=,iv:6KhPhY4KO4ps3vOsreYLCz5ddr+kKfGdVZDvPle3lDs=,tag:GCxKYteGRN993ey+TUv+lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
