---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name speedtest-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - vg.monosense.io:9798
  metricsPath: /metrics
  scrapeInterval: 60m
  scrapeTimeout: 60s
  honorTimestamps: true
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
