---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-nfs-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-nfs
          httpConnection:
            protocol: https
            host: "{{ .truenas_host }}"
            port: "443"
            apiKey: "{{ .truenas_api_key }}"
            allowInsecure: false
          sshConnection:
            host: "{{ .truenas_host }}"
            port: "22"
            username: "{{ .truenas_user }}"
            password: "{{ .truenas_password }}"
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: raid-z1/k8s/nfs/vols
            detachedSnapshotsDatasetParentName: raid-z1/k8s/nfs/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareCommentTemplate: "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            shareHost: "{{ .truenas_host }}"
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: ["172.16.11.0/24"]
            shareMaprootUser: root
            shareMaprootGroup: wheel
            shareMapallUser: ""
            shareMapallGroup: ""
  dataFrom:
    - extract:
        key: democratic-csi
