apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: trunas-nfs
  resources:
    requests:
      storage: 1TiB
