---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: paperless
  namespace: selfhosted
spec:
  sourcePVC: library-paperless-0
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: paperless-restic-s3
    cacheCapacity: 15Gi
    volumeSnapshotClassName: ceph-block
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d