---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: minio
  namespace: flux-system
spec:
  suspend: false
  interval: 12h
  path: ./infrastructure/terraform/minio
  sourceRef:
    kind: GitRepository
    name: home-cluster
    namespace: flux-system
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  runnerPodTemplate:
    spec:
      env:
        - name: OP_CONNECT_HOST
          value: http://onepassword-connect.monosense.io:8080
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tf-controller-secrets
              key: OP_CONNECT_TOKEN