---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-iscsi-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-iscsi
          httpConnection:
            protocol: http
            host: "san.monosense.io"
            port: "443"
            apiKey: "eyJhIjoiZWNhMDgzM2Y2MDhiNTc0NWFmMDMwMzA3YTk5YmRiYjQiLCJ0IjoiNGJmZTIxM2EtZDA1ZC00YmFiLWE1NjgtNzg0ZDRkOWJlNGRkIiwicyI6IllUTmxaR1EwWTJZdFlUTXlaQzAwTVRRNUxXRmxZVFV0WWpjNE9HUTNNak0yWWpGaiJ9"
            allowInsecure: false
          sshConnection:
            host: "san.monosense.io"
            port: "22"
            username: "root"
            privateKey: |
              -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
              QyNTUxOQAAACCQMhTelJII+8oRqQY71ZHeDd6jQSKeKu+/H4KktgARyQAAAJiUlWUZlJVl
              GQAAAAtzc2gtZWQyNTUxOQAAACCQMhTelJII+8oRqQY71ZHeDd6jQSKeKu+/H4KktgARyQ
              AAAEBGrk9+QlY2rXWUkWzkA3jUDHx0YsbtSw8rhdv3dy7GOJAyFN6Ukgj7yhGpBjvVkd4N
              3qNBIp4q778fgqS2ABHJAAAAFXJvb3RAc2FuLm1vbm9zZW5zZS5pbw==
              -----END OPENSSH PRIVATE KEY-----
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: raid-z1/k8s/iscsi/vols
            detachedSnapshotsDatasetParentName: raid-z1/k8s/iscsi/snaps
            zvolCompression: gzip
            zvolDedup: false
            zvolEnableReservation: false
            zvolBlocksize: 16K
          iscsi:
            targetPortal: "san.monosense.io:3260"
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
            namePrefix: ""
            nameSuffix: ""
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 4096
            extentRpm: "SSD"
            extentAvailThreshold: 0
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi