---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/kube-prometheus-stack/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: production-alertmanager
    - name: production-rook-ceph-cluster
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-kube-prometheus-stack-addons
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/kube-prometheus-stack/addons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: production-kube-prometheus-stack
