---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-talos-backup
  namespace: flux-system
spec:
  path: ./kubernetes/apps/talos-system/talos-backup/app
  sourceRef:
    kind: GitRepository
    name: home-cluster
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  interval: 10m
  retryInterval: 1m
  timeout: 5m
